### ISSUE TITLE
unicode?

### ISSUE THREAD

**Issue by sje30** [benmarwick/huskydown#3]
Hi Ben,

do you take a view on whether to support "unicode" formatting in markdown?  e.g. writing α rather than $\alpha$ in your markdown?  I don't recall the details, but I think preferring unicode helped with .md to .docx conversions.   But then you need to use an appropriate tex engine.

**Comment by benmarwick** [comment]
I did a bit of experimentation on this in 2014 and documented it here: https://gist.github.com/benmarwick/4fb6f222443493e3c864 At that time it seemed that HTML and LaTeX codes for special symbols were the most versatile (with PDF as the desired output) so I went with those. 

But I just gave that gist a quick test again, and it seems I can't get use any method to get lower case Greek letters to show in PDF with xelatex. So that's a bit surprising (I've updated the gist). I can get these letters with pdflatex and $..$ notation, but then I can't have any unescaped unicode characters in there, so all symbols have to be $..$ or HTML. 

So I guess I don't have a strong opinion about those. When outputting PDF I'm using xelatex so I can use unicode and certain fonts. But mostly I'm outputting Word docs for my own work (since that what publishers require for article submission), and using the unicode characters in the Rmd works fine, with no need to worry about tex engines or LaTeX packages, etc. But it seems like I use these characters just infrequently enough that I have to relearn how to each time!

What about you, what's your approach?

**Comment by sje30** [comment]
Thanks, v. useful.


My approach (about a year+ ago) was to keep a m/script in .md and then use pandoc to convert to .docx for colleagues, and pdf for me.  I *thought* I had good success with unicode in the doc, but I will need to check.  Did you use https://ctan.org/pkg/unicode-math?lang=en (I think I needed to).

Will check soonish, as I need to update my latex notes for the new academic year!

**Comment by sje30** [comment]
p.s. I recall needing to install a new font, tex-gyre, for this to work.
