### ISSUE TITLE
Links in the README

### ISSUE THREAD

**Issue by sarahcn** [benmarwick/huskydown#5]
It appears UW has moved the content linked to here:
https://grad.uw.edu/for-students-and-post-docs/thesisdissertation/final-submission-of-your-thesisdissertation/

Good luck finding that original content, though! I've been hard pressed to find a clear template for the UW dissertation.

**Comment by benmarwick** [comment]
Thanks for spotting that, I've fixed it now. 

I think the UW grad school has become quite hands-off about templates and formatting for dissertations. Some faculty have even suggested there's no need for a pkg like this because students can basically do what they want for formatting. The UW only gives official templates for the [title page](https://grad.uw.edu/wordpress/wp-content/uploads/sample-phd-title.pdf), [copyright page](https://grad.uw.edu/wordpress/wp-content/uploads/sample-copyright-1.pdf), and [abstract](https://grad.uw.edu/wordpress/wp-content/uploads/sample-abstract.pdf)

Beyond that I think you're free to do what you like! Unless your committee have specific preferences, that should probably be the priority. If they don't, then you're free to choose, and could use a beautiful template like [dissertate](http://dissertate.io/) (as this pkg does).

**Comment by ccurtis7** [comment]
It seems that content has been moved yet again. Here's a link to the formatting guidelines:

https://grad.uw.edu/for-students-and-post-docs/thesisdissertation/formatting-guidelines/
